<?php
http://stackoverflow.com/questions/20770544/hit-counter-with-php-and-mysql-database

http://ibloghost.blogspot.com/2013/02/how-to-make-visitors-counter-using-php.html
http://php.about.com/od/finishedphp1/qt/hit_counter.htm
http://prabupasundan-berbagi.blogspot.com/2013/12/membuat-counter-visitor-dengan-php-mysql.html
http://informatika11d.wordpress.com/2013/04/02/php-mysql-membuat-counter-website-sederhana/
<?php
$server = “localhost”;
$username = “root”;
$password = “”;
$database = “visitors”;

// Koneksi dan memilih database di server
mysql_connect($server,$username,$password) or die(“Koneksi gagal”);
mysql_select_db($database) or die(“Database tidak bisa dibuka”);
?>

3. tinggal buat interficenya, caranya buat file php satu lagi kasih nama index.php ketikan script berikut:
<?php
//Koneksi ke server    include(‘koneksi.php’);
//pilih database    mysql_select_db($namadb);
$query = “select nomer from counter”;
$result = mysql_query($query);
$tcount = mysql_fetch_array($result);
if(!$tcount["nomer"])    {
$result = mysql_query(“insert into counter values (1)”);
}
$tcount = $tcount["nomer"]+1;
$query1 = “update counter SET nomer=$tcount”;
$result1 = mysql_query($query1);
echo “<p align=’center’>Visitors ke- <b><i>$tcount</i></b></p>”;?>

udah slsae dah cukup simple kan..
live demo bisa dilihat di http://codeenter.net/
http://media-kreatif.com/home/post/49/tutorial-membuat-script-counter-pengunjung-gambar-dengan-php-dan-mysql.prm
// Error reporting:
error_reporting(E_ALL^E_NOTICE);

// Including the DB connection file:
require 'connect.php';

$extension='';
$files_array = array();


/* Opening the thumbnail directory and looping through all the thumbs: */

$dir_handle = @opendir($directory) or die("There is an error with your file directory!");

while ($file = readdir($dir_handle)) 
{
	/* Skipping the system files: */
	if($file{0}=='.') continue;
	
	/* end() returns the last element of the array generated by the explode() function: */
	$extension = strtolower(end(explode('.',$file)));
	
	/* Skipping the php files: */
	if($extension == 'php') continue;

	$files_array[]=$file;
}

/* Sorting the files alphabetically */
sort($files_array,SORT_STRING);

$file_downloads=array();

$result = mysql_query("SELECT * FROM download_manager");

if(mysql_num_rows($result))
while($row=mysql_fetch_assoc($result))
{
	/* 	The key of the $file_downloads array will be the name of the file,
		and will contain the number of downloads: */
		
	$file_downloads[$row['filename']]=$row['downloads'];
}

?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>PHP &amp; MySQL File Download Counter | Tutorialzine demo</title>

<link rel="stylesheet" type="text/css" href="styles.css" />
<link rel="stylesheet" type="text/css" href="fancybox/jquery.fancybox-1.2.6.css" media="screen" />

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
<script type="text/javascript" src="script.js"></script>

</head>

<body>

<h1>PHP &amp; MySQL File Download Counter</h1>
<h2>Go back <a href="http://tutorialzine.com/2010/02/php-mysql-download-counter/">to the tutorial &raquo;</a></h2>

    
<div id="file-manager">

    <ul class="manager">
    <?php 

        foreach($files_array as $key=>$val)
        {
            echo '<li><a href="download.php?file='.urlencode($val).'">'.$val.' 
                    <span class="download-count" title="Times Downloaded">'.(int)$file_downloads[$val].'</span> <span class="download-label">download</span></a>
                    </li>';
        }
    
    ?>
  </ul>

</div>


<p class="tutInfo">This is a tutorialzine demo. View the <a href="http://tutorialzine.com/2010/02/php-mysql-download-counter/">original tutorial</a>, or download the <a href="demo.zip">source files</a>.</p>


</body>
</html>
